Refactor overview to fix TypeError
Error: TypeError: cannot concatenate 'str' and 'RecordList' objects.
Cause: File "/app/slack/app.py", line 37, in POST: return "\n" + overview()